STATUSES = (
   "Here! Have a hug!",
   "You deserve a hug!",
   "I don't know who needs this today, but here, have a hug.",
   "Hug a friend today!",
   "Hugs are so underrated!",
   "It's only a hug if it's from the Hughes region of France; otherwise it's just sparkling cuddles.",
   "I just took a DNA test, turns out I'm 100% hugs!",
   "What am I supposed to do with these 30-50 feral hugs?",
   "You get a hug! And you get a hug! And you get a hug! Everyone gets a hug!!!",
   "A hug is worth a thousand words!",
   "Did you know?\n\nStudies have shown that a hug a day can reduce stress, improve immune system function, lower your risk of heart disease, and ease depression!\n\nHug someone today!",
   "A hug a day keeps the doctor away.",
   "Need a hug?",
   "Make hugs, not war!",
   "1. Give hugs.\n2. ...\n3. Profit?\n\n\n(Kidding of course! The hugs ARE the profit!)",
   "Hugs.\n\n\n\nThat's it, that's the tweet.",
   "Nobody, nobody at all:\n\nMe: Here, have a hug!",
   "Hugging a friend makes you feel better, makes them feel better, and makes the world a better place!\n\n\nThanks for coming to my TED talk.",
   "*Taps mic* \"Hi... Is this thing on?\"\n\n\"Hello everyone here's a hug!\"",
   "Hi, I'm a Twitter bot. You may know me from my hit singles: \"You Deserve A Hug!\", \"You Can Never Get Too Many Hugs\", and the ever popular \" Hugs Are Waaaay Underrated!!!\"",
   "Sex is good, but have you ever tried just a platonic, no strings attached hug with a close friend?",
   "🌹Roses are red\n💙Violets are blue\n🏠Tag a friend with this hug\n🤗So they'll feel hugged too!",
   "#SocialDistancing doesn't mean we need to be socially isolated! Send a virtual hug to someone today!",
   "Missing that physical touch? Here's a virtual hug!",
   "With talk about vaccines in the air, does that mean we can soon have in-person hugs???",
   "Here's a small hug the size of a large hug!",
   "I love hugs!\n\nSend tweet!",
   "Friends be like \"I know a spot\" and then just give you a hug.",
   "Hugs are great!\n\n\n\n\n\n\nⓘ Official sources all agree this is the case",
   "I'm a:\n⚪️ Man\n⚪️ Woman\n🔘 Twitter Bot\n\nLooking for a:\n⚪️ Man\n⚪️ Woman\n🔘 Hug!",
   "The snuggle is real... 🤗",
   "Don't forget to wear your mask! It's like a hug for your face 😷\n\nAnd while you're here, have a virtual hug 🤗",
   "Do you need a hug?\n\nYes          Yes             Yes\n 👇           👇             👇",
   "My \"Free Hugs!\" t-shirt is raising a lot of questions already answered by my \"Free Hugs!\" t-shirt.",
)
