STATUSES = (
   "Here! Have a hug!",
   "You deserve a hug!",
   "I don't know who needs this today, but here, have a hug.",
   "Hug a friend today (if they want it)!",
   "Hugs are so underrated!",
   "It's only a hug if it's from the Hughes region of France; otherwise it's just sparkling cuddles.",
   "I just took a DNA test, turns out I'm 100% hugs!",
   "What am I supposed to do with these 30-50 feral hugs?",
   "You get a hug! And you get a hug! And you get a hug! Everyone gets a hug!!!",
   "A hug is worth a thousand words!",
   "Did you know?\n\nStudies have shown that a hug a day can reduce stress, improve immune system function, lower your risk of heart disease, and ease depression!\n\nHug someone today!",
   # Should probably keep this commented until #coronavirus is over
   # "A hug a day keeps the doctor away.",
   "Need a hug?",
   "Make hugs, not war!",
   "1. Give hugs.\n2. ...\n3. Profit?\n\n\n(Kidding of course! The hugs ARE the profit!)",
   "Hugs.\n\n\n\nThat's it, that's the tweet.",
   "Nobody, nobody at all:\n\nMe: Here, have a hug!",
   "Hugging a friend makes you feel better, makes them feel better, and makes the world a better place!\n\n\nThanks for coming to my TED talk.",
   "*Taps mic* \"Hi... Is this thing on?\"\n\n\"Hello everyone here's a hug!\"",
   "Hi, I'm a Twitter bot. You may know me from my hit singles: \"You Deserve A Hug!\", \"You Can Never Get Too Many Hugs\", and the ever popular \" Hugs Are Waaaay Underrated!!!\"",
   "Sex is good, but have you ever tried just a platonic, no strings attached hug with a close friend?",
   "Roses are red\nViolets are blue,\nTag a friend with this hug\nSo they'll feel hugged too!",
   "#SocialDistancing doesn't mean we need to be socially isolated! Send a virtual hug to someone today!",
   "Missing that physical touch? Here's a virtual hug!",
   "Coronavirus is a bitch! Stay inside; send virtual hugs instead!",
)