name: hug-bot
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2/3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run bot
        run: |
          python hug-bot.py
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}

